<https://github.com/PolymathicAI/xVal>


In [1]:
import os

os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = "0.95"

In [2]:
import jax.numpy as jnp  # Oddly works in colab to set gpu

arr = jnp.array([1, 2, 3])
arr.devices()

{cuda(id=0)}

In [3]:
import icecream
from icecream import ic

icecream.install()
ic_disable = True
if ic_disable:
    ic.disable()
ic.configureOutput(includeContext=True, contextAbsPath=True)

In [4]:
import os
import ast

from datetime import datetime as dt
from torch.utils.data import Dataset

import hephaestus as hp
import jax
import jax.numpy as jnp
import numpy as np
import optax
import pandas as pd
from flax.training import train_state
from icecream import ic
from jax import random
from flax import struct
from jax.tree_util import tree_flatten
from torch.utils.tensorboard import SummaryWriter
from tqdm.notebook import tqdm, trange

pd.options.mode.copy_on_write = True

2024-05-13 01:57:38.216793: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [5]:
def line2df(line, idx):
    data_rows = []
    line = ast.literal_eval(line)
    for i, time_step in enumerate(line["data"]):
        row = {"time_step": i}
        # Add position data for each planet
        for j, position in enumerate(time_step):
            row[f"planet{j}_x"] = position[0]
            row[f"planet{j}_y"] = position[1]
        data_rows.append(row)

    df = pd.DataFrame(data_rows)
    description = line.pop("description")
    step_size = description.pop("stepsize")
    for k, v in description.items():
        for k_prop, v_prop in v.items():
            df[f"{k}_{k_prop}"] = v_prop
    df["time_step"] = df["time_step"] * step_size
    df.insert(0, "idx", idx)

    return df

In [6]:
files = os.listdir("data")
if "planets.parquet" not in files:
    with open("data/planets.data") as f:
        data = f.read().splitlines()

        dfs = []
        for idx, line in enumerate(tqdm(data)):
            dfs.append(line2df(line, idx))
        print("Concatenating dfs...")
        df = pd.concat(dfs)
    df.to_parquet("data/planets.parquet")
else:
    df = pd.read_parquet("data/planets.parquet")

In [7]:
# Get min, mean, and max number of time steps
df.groupby("idx").count().time_step.agg(["min", "mean", "max"])

min     30.000000
mean    44.511656
max     59.000000
Name: time_step, dtype: float64

In [8]:
class SimpleDS(Dataset):
    def __init__(self, df):
        # Add nan padding to make sure all sequences are the same length
        # use the idx column to group by
        self.max_seq_len = df.groupby("idx").count().time_step.max()

        self.df = df
        self.batch_size = self.max_seq_len

        self.special_tokens = ["[PAD]", "[NUMERIC_MASK]", "[MASK]"]
        self.cat_mask = "[MASK]"
        self.numeric_mask = "[NUMERIC_MASK]"

        self.col_tokens = [col_name for col_name in df.columns if col_name != "idx"]

        self.tokens = self.special_tokens + self.col_tokens

        self.token_dict = {token: i for i, token in enumerate(self.tokens)}
        self.token_decoder_dict = {i: token for i, token in enumerate(self.tokens)}
        self.n_tokens = len(self.tokens)
        self.numeric_indices = jnp.array(
            [self.tokens.index(i) for i in self.col_tokens]
        )

        self.numeric_mask_token = self.tokens.index(self.numeric_mask)

    def __len__(self):
        return df.idx.max() + 1  # probably should be max idx + 1 thanks

    def __getitem__(self, set_idx):
        batch = self.df.loc[
            df.idx == set_idx, [col for col in self.df.columns if col != "idx"]
        ]
        batch = np.array(batch.values)
        # Add padding
        batch_len, n_cols = batch.shape
        pad_len = self.max_seq_len - batch_len
        padding = np.full((pad_len, n_cols), jnp.nan)
        batch = np.concatenate([batch, padding], axis=0)
        return batch

In [9]:
np.full((3, 3), np.nan)

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])

In [10]:
train_ds = SimpleDS(df)

In [11]:
time_series_regressor = hp.simple_time_series.SimplePred(train_ds, d_model=64 * 4)

In [12]:
train_ds[0]

array([[ 0.        ,  1.56006022, -0.85443699, ...,         nan,
                nan,         nan],
       [ 0.46511628,  1.68985799, -0.5143588 , ...,         nan,
                nan,         nan],
       [ 0.93023256,  1.75358875, -0.15420858, ...,         nan,
                nan,         nan],
       ...,
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan],
       [        nan,         nan,         nan, ...,         nan,
                nan,         nan]])

In [13]:
def make_batch(ds: SimpleDS, start: int, length: int):
    data = []
    for i in range(start, length + start):
        data.append(ds[i])

    return jnp.array(data)


batch = make_batch(train_ds, 0, 4)

In [14]:
vars = time_series_regressor.init(random.PRNGKey(0), batch)

x = time_series_regressor.apply(vars, batch)

In [15]:
x

Array([[[-0.00999765, -0.00999765, -0.00999765, ..., -0.00999765,
         -0.00999765, -0.00999765],
        [ 0.00572604,  0.00572604,  0.00572604, ...,  0.00572604,
          0.00572604,  0.00572604],
        [ 0.00717407,  0.00717407,  0.00717407, ...,  0.00717407,
          0.00717407,  0.00717407],
        ...,
        [-0.15913501, -0.15913501, -0.15913501, ..., -0.15913501,
         -0.15913501, -0.15913501],
        [-0.18229163, -0.18229163, -0.18229163, ..., -0.18229163,
         -0.18229163, -0.18229163],
        [-0.14735968, -0.14735968, -0.14735968, ..., -0.14735968,
         -0.14735968, -0.14735968]],

       [[ 0.01031545,  0.01031545,  0.01031545, ...,  0.01031545,
          0.01031545,  0.01031545],
        [ 0.03705181,  0.03705181,  0.03705181, ...,  0.03705181,
          0.03705181,  0.03705181],
        [ 0.0409942 ,  0.0409942 ,  0.0409942 , ...,  0.0409942 ,
          0.0409942 ,  0.0409942 ],
        ...,
        [-0.15913501, -0.15913501, -0.15913501, ..., -

In [16]:
batch.shape

(4, 59, 26)

In [17]:
def calculate_memory_footprint(params):
    """Calculate total memory footprint of JAX model parameters."""
    total_bytes = 0
    # Flatten the parameter tree structure into a list of arrays
    flat_params, _ = tree_flatten(params)
    for param in flat_params:
        # Calculate bytes: number of elements * size of each element
        bytes_per_param = param.size * param.dtype.itemsize
        total_bytes += bytes_per_param
    return total_bytes

In [27]:
def create_causal_mask(tensor: jnp.ndarray):
    """Create a causal mask to mask out future values."""
    mask = jnp.tril(jnp.ones((tensor.shape[0], tensor.shape[1])))
    return mask


def create_padding_mask(tensor: jnp.ndarray):
    """Create a padding mask to mask out padded values."""
    mask = jnp.isnan(tensor)
    return mask


def mask_array(tensor: jnp.array):
    """Create a mask for the tensor"""
    causal_mask = create_causal_mask(tensor)
    padding_mask = create_padding_mask(tensor)
    mask = jnp.logical_or(causal_mask, padding_mask)
    return mask

In [30]:
jnp.array(train_ds[0]).shape

(59, 26)

In [37]:
def create_causal_mask(batch_size, time_steps, n_columns):
    # Create a 2D mask for the time steps
    # Only future steps are masked
    mask = jnp.triu(np.ones((time_steps, time_steps)), k=1).astype(bool)

    # Expand the mask across the batch size and n_columns
    # The resulting mask will have the shape: (batch_size, time_steps, n_columns, time_steps)
    mask = jnp.tile(mask[:, None, :], (1, n_columns, 1))
    mask = jnp.tile(mask[None, :, :, :], (batch_size, 1, 1, 1))

    return mask


# Example usage
batch_size = 2
time_steps = 4
n_columns = 3
mask = create_causal_mask(batch_size, time_steps, n_columns)
example_tensor = jnp.ones((batch_size, time_steps, n_columns))
masked_tensor = jnp.where(mask, example_tensor, jnp.nan)
masked_tensor

ValueError: Incompatible shapes for broadcasting: shapes=[(2, 4, 3, 4), (2, 4, 3), ()]

In [33]:
create_causal_mask(jnp.ones((4, 5)))

Array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.]], dtype=float32)

In [21]:
mts_root_key = random.PRNGKey(44)
mts_main_key, ts_params_key, ts_data_key = random.split(mts_root_key, 3)


def clip_gradients(gradients, max_norm):
    total_norm = jnp.sqrt(sum(jnp.sum(jnp.square(grad)) for grad in gradients.values()))
    scale = max_norm / (total_norm + 1e-6)
    clipped_gradients = jax.tree_map(
        lambda grad: jnp.where(total_norm > max_norm, grad * scale, grad), gradients
    )
    return clipped_gradients


# @jax.jit
def calculate_loss(params, state, inputs, dataset: SimpleDS):
    out = state.apply_fn(
        {"params": params},
        hp.mask_tensor(inputs, dataset, prng_key=ts_data_key),
    )

    # Create mask for nan inputs
    nan_mask = jnp.isnan(inputs)
    # inputs = jnp.where(nan_mask, jnp.zeros_like(inputs), inputs)
    # out = jnp.where(nan_mask, jnp.zeros_like(out), out)

    loss_raw = optax.squared_error(out, inputs)
    loss = jnp.compress(~nan_mask, loss_raw).mean()
    # print(f"Loss ITEM!!!! {loss.item()}")
    return loss


# @jax.jit
def eval_step(state: train_state.TrainState, batch):
    def loss_fn(params):
        return calculate_loss(params, state, batch, train_ds)

    # (loss, individual_losses), grad = grad_fn(state.params)
    loss, loss_dict = loss_fn(state.params)
    return loss, loss_dict


@jax.jit
def train_step(state: train_state.TrainState, batch):
    def loss_fn(params):
        return calculate_loss(params, state, batch, train_ds)

    grad_fn = jax.value_and_grad(loss_fn)

    # (loss, individual_losses), grad = grad_fn(state.params)
    loss, grad = grad_fn(state.params)
    # grad = replace_nans(grad)
    # grad = clip_gradients(grad, 1.0)
    state = state.apply_gradients(grads=grad)

    return state, loss


def create_train_state(model, prng, batch, lr):
    params = model.init(prng, batch)
    # optimizer = optax.chain(optax.adam(lr))
    optimizer = optax.chain(optax.clip_by_global_norm(0.4), optax.adam(lr))
    # optimizer_state = optimizer.init(params)
    return train_state.TrainState.create(
        apply_fn=model.apply,
        params=params["params"],
        tx=optimizer,
        # tx_state=optimizer_state,
    )


batch_size = 2
# batch = train_ds[0]

state = create_train_state(time_series_regressor, mts_main_key, batch, 0.0001)

In [22]:
from torch.utils.data import DataLoader

from torch.utils.data import DataLoader


In [23]:
writer_name = "SimpleTS"

writer_time = dt.now().strftime("%Y-%m-%dT%H:%M:%S")

train_summary_writer = SummaryWriter(
    "runs/" + writer_time + "_wow_" + writer_name + "_train"
)


test_set_key = random.PRNGKey(4454)

train_data_loader = DataLoader(train_ds, batch_size=512, shuffle=True)
batch_count = 0
for j in trange(2, desc=f"epochs for {train_summary_writer.log_dir}"):
    # arrs = train_data_loader()
    for i in tqdm(train_data_loader, leave=False, desc="batches"):
        # for i in trange(len(pre_train) // batch_size, leave=False):
        # for i in trange(len(pre_train) // batch_size //10, leave=False):
        # batch = make_batch(train_ds, i[0], 4)

        state, loss = train_step(state, jnp.array(i))
        if jnp.isnan(loss):
            raise ValueError("Nan Value in loss, stopping")
        batch_count += 1

        if batch_count % 1 == 0:
            train_summary_writer.add_scalar(
                "loss/loss", np.array(loss.item()), batch_count
            )

epochs for runs/2024-05-13T01:58:49_wow_SimpleTS_train:   0%|          | 0/14 [00:00<?, ?it/s]

batches:   0%|          | 0/245 [00:00<?, ?it/s]

batches:   0%|          | 0/245 [00:00<?, ?it/s]

batches:   0%|          | 0/245 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [50]:
test_result = jnp.squeeze(
    state.apply_fn({"params": state.params}, jnp.array([train_ds[0]]))
)
test_result

Array([[1.4373543, 1.4373543, 1.4373913, ..., 1.4373543, 1.4373543,
        1.4373543],
       [1.4121699, 1.4121698, 1.4121699, ..., 1.4121699, 1.4121699,
        1.4121699],
       [1.3919055, 1.3919055, 1.3919055, ..., 1.3919055, 1.3919055,
        1.3919055],
       ...,
       [2.2000782, 2.2000782, 2.2000782, ..., 2.2000782, 2.2000782,
        2.2000782],
       [2.1688452, 2.1688452, 2.1688452, ..., 2.1688452, 2.1688452,
        2.1688452],
       [2.1502194, 2.1502194, 2.1502194, ..., 2.1502194, 2.1502194,
        2.1502194]], dtype=float32)

In [46]:
jnp.array(train_ds[0]).shape, test_result.shape

((59, 26), (1, 59, 26))

In [48]:
jnp.squeeze(test_result).shape

(59, 26)

In [52]:
df_pred = pd.DataFrame(test_result)
df_actual = pd.DataFrame(train_ds[0])

In [54]:
df_pred

0         1         2         3         4         5         6   \
0    1.437354  1.437354  1.437391  1.437354  1.437354  1.437354  1.437354   
1    1.412170  1.412170  1.412170  1.412170  1.412170  1.412170  1.412170   
2    1.391906  1.391906  1.391906  1.391906  1.391906  1.391906  1.391906   
3    1.366370  1.366354  1.366348  1.366347  1.366355  1.366348  1.366363   
4    1.323469  1.321951  1.321842  1.321652  1.321838  1.321779  1.322127   
5    1.271234  1.243167  1.242631  1.240222  1.241583  1.240969  1.244538   
6    2.286670  1.145433  1.144320  1.115955  1.124038  1.120317  1.162274   
7    4.521352  1.146990  1.187843  0.945027  0.935768  0.912765  1.324656   
8    3.774994  1.007358  1.450285  0.487091  0.141636  0.032512  1.942989   
9    4.412226  0.588430  1.866369  0.349090 -0.716906 -1.021551  2.443130   
10   5.019538  0.227126  1.888445  0.791654 -0.740773 -1.389133  2.334280   
11   5.358994 -0.157142  1.874660  1.107809 -0.432813 -1.539848  2.180945   
12   5.563088 -0.667493  1.897134  1.186427  0.060345 -1.626834  2.064752   
13   5.883640 -1.058375  1.881047  1.000066  0.534132 -1.786740  1.954329   
14   6.303962 -1.234468  1.797595  0.633750  0.895178 -2.012424  1.785623   
15   6.837324 -1.339337  1.672579  0.024722  1.110208 -2.174672  1.599338   
16   7.427869 -1.491255  1.433858 -0.485388  1.030484 -2.273295  1.329829   
17   7.982532 -1.674590  1.101997 -0.758202  0.738396 -2.346509  0.997491   
18   8.481820 -1.786896  0.806491 -0.997023  0.222622 -2.342515  0.705007   
19   8.934710 -1.828657  0.440821 -0.973854 -0.217193 -2.368635  0.369906   
20   9.377786 -1.917150  0.149085 -0.789178 -0.602083 -2.473271  0.105496   
21   9.834937 -2.024716 -0.164430 -0.514289 -0.915306 -2.598916 -0.173065   
22  10.318847 -2.092089 -0.485429 -0.121387 -1.087726 -2.689350 -0.458171   
23  10.813057 -2.093420 -0.791364  0.356859 -1.016962 -2.706887 -0.730867   
24  11.298434 -2.022815 -1.020691  0.780895 -0.666634 -2.682947 -0.932477   
25  11.766288 -1.889057 -1.299571  1.017477 -0.159251 -2.673756 -1.185550   
26  12.203382 -1.689771 -1.584885  0.984972  0.317080 -2.680233 -1.481935   
27  12.628815 -1.409874 -1.850814  0.727735  0.684783 -2.650165 -1.788742   
28  13.072464 -1.121183 -2.018804  0.276828  1.009536 -2.555903 -2.028759   
29  13.549956 -0.829171 -2.117776 -0.274666  1.093311 -2.372162 -2.205609   
30  14.052283 -0.465339 -2.066869 -0.695588  0.863206 -2.096478 -2.213705   
31  14.533471 -0.021433 -1.886216 -0.966109  0.517291 -1.748452 -2.060690   
32  15.001737  0.396265 -1.717975 -0.936786  0.120868 -1.439233 -1.941935   
33  15.464746  0.766099 -1.600744 -0.746933 -0.290252 -1.148647 -1.948827   
34  15.937218  1.056247 -1.457762 -0.471972 -0.578229 -0.829984 -1.970247   
35  16.436983  1.365839 -1.266414 -0.195082 -0.826373 -0.581953 -1.915703   
36  16.958950  1.585731 -1.004783  0.178392 -0.922430 -0.374385 -1.768340   
37  17.477139  1.780047 -0.640145  0.569267 -0.708304 -0.151685 -1.591688   
38  17.973789  1.901352 -0.230850  0.813695 -0.259706  0.110963 -1.539996   
39  18.446491  1.905706  0.052176  0.836801  0.100380  0.347887 -1.663893   
40  18.911346  1.811662  0.330609  0.686024  0.426084  0.473132 -1.817253   
41  19.393915  1.724316  0.514841  0.401804  0.650435  0.680229 -1.854092   
42  19.892784  1.553593  0.841788  0.052532  0.817920  1.014394 -1.757624   
43  20.391842  1.272578  1.301042 -0.346223  0.820290  1.418135 -1.625464   
44   2.199863  2.199863  2.199863  2.199863  2.199863  2.199863  2.199863   
45   2.242986  2.242986  2.242986  2.242986  2.242986  2.242986  2.242986   
46   2.293994  2.293994  2.293994  2.293994  2.293994  2.293994  2.293994   
47   2.322799  2.322799  2.322799  2.322799  2.322799  2.322799  2.322799   
48   2.325436  2.325436  2.325436  2.325436  2.325436  2.325436  2.325436   
49   2.310490  2.310490  2.310490  2.310490  2.310490  2.310490  2.310490   
50   2.294999  2.294999  2.294999  2.294999  2.294999  2.294999  2.294999   
51   2.

In [55]:
df_actual

0         1         2         3         4         5         6   \
0    0.000000  1.560060 -0.854437  0.720639  0.691729  0.944008  2.700632   
1    0.465116  1.689858 -0.514359  0.333295  0.942289  0.681604  2.785811   
2    0.930233  1.753589 -0.154209 -0.124995  0.992368  0.412951  2.845461   
3    1.395349  1.748068  0.212022 -0.556775  0.831727  0.140540  2.879232   
4    1.860465  1.673573  0.569904 -0.870579  0.494812 -0.133144  2.887018   
5    2.325581  1.533811  0.905607 -1.000151  0.053178 -0.405638  2.868949   
6    2.790698  1.335526  1.206832 -0.918192 -0.399688 -0.674530  2.825381   
7    3.255814  1.087824  1.463513 -0.641980 -0.767958 -0.937474  2.756889   
8    3.720930  0.801365  1.668203 -0.229808 -0.973515 -1.192211  2.664256   
9    4.186047  0.487549  1.816168  0.231092 -0.972449 -1.436585  2.548458   
10   4.651163  0.157822  1.905225  0.642811 -0.764575 -1.668554  2.410650   
11   5.116279 -0.176870  1.935436  0.917559 -0.393801 -1.886207  2.252158   
12   5.581395 -0.506443  1.908720  0.996574  0.061000 -2.087774  2.074456   
13   6.046512 -0.821885  1.828463  0.862921  0.502832 -2.271633  1.879159   
14   6.511628 -1.115352  1.699162  0.545212  0.837490 -2.436322  1.668004   
15   6.976744 -1.380170  1.526119  0.111347  0.993853 -2.580544  1.442838   
16   7.441860 -1.610795  1.315203 -0.346239  0.939015 -2.703172  1.205599   
17   7.906977 -1.802741  1.072663 -0.730422  0.685027 -2.803255  0.958309   
18   8.372093 -1.952503  0.804994 -0.959957  0.286020 -2.880023  0.703051   
19   8.837209 -2.057485  0.518845 -0.986439 -0.173427 -2.932885  0.441961   
20   9.302326 -2.115938  0.220954 -0.804305 -0.596103 -2.961438  0.177211   
21   9.767442 -2.126912 -0.081893 -0.451965 -0.892498 -2.965464 -0.089004   
22  10.232558 -2.090237 -0.382893 -0.003872 -0.999585 -2.944932 -0.354477   
23  10.697674 -2.006509 -0.675252  0.444975 -0.894252 -2.899997 -0.617010   
24  11.162791 -1.877113 -0.952210  0.799049 -0.598498 -2.831004 -0.874419   
25  11.627907 -1.704255 -1.207074  0.982727 -0.175061 -2.738478 -1.124556   
26  12.093023 -1.491017 -1.433278  0.956673  0.285841 -2.623132 -1.365315   
27  12.558140 -1.241423 -1.624455  0.726448  0.685888 -2.485858 -1.594656   
28  13.023256 -0.960518 -1.774551  0.341306  0.939879 -2.327724 -1.810607   
29  13.488372 -0.654444 -1.877989 -0.116555  0.994010 -2.149972 -2.011292   
30  13.953488 -0.330492 -1.929876 -0.549761  0.837182 -1.954013 -2.194933   
31  14.418605  0.002871 -1.926281 -0.866538  0.503039 -1.741415 -2.359874   
32  14.883721  0.336052 -1.864565 -1.000002  0.062565 -1.513904 -2.504591   
33  15.348837  0.658485 -1.743757 -0.922043 -0.390993 -1.273345 -2.627708   
34  15.813953  0.958914 -1.564952 -0.649103 -0.761665 -1.021741 -2.728011   
35  16.279070  1.225853 -1.331663 -0.238785 -0.970834 -0.761211 -2.804462   
36  16.744186  1.448211 -1.050060  0.222075 -0.973830 -0.493987 -2.856214   
37  17.209302  1.616059 -0.729007  0.635585 -0.769602 -0.222387 -2.882622   
38  17.674419  1.721456 -0.379819  0.913575 -0.401274  0.051193 -2.883258   
39  18.139535  1.759203 -0.015710  0.996587  0.052806  0.324305 -2.857916   
40  18.604651  1.727385  0.349052  0.866830  0.495796  0.594465 -2.806627   
41  19.069767  1.627587  0.700142  0.552081  0.833240  0.859181 -2.729662   
42  19.534884  1.464716  1.024199  0.119611  0.993425  1.115970 -2.627536   
43  20.000000  1.246492  1.309683 -0.338443  0.942632  1.362393 -2.501014   
44        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
45        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
46        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
47        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
48        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
49        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
50        NaN       NaN       NaN       NaN       NaN       NaN       NaN   
51     

In [ ]:
model_name = f"big_train_{dt.now()}_"

current_dir = os.getcwd()

if not os.path.exists("./pre_trained_models/"):
    os.makedirs("./pre_trained_models/")

path = os.path.join(current_dir, "./pre_trained_models/")


ckpt_dir = f"./pre_trained_models/{model_name}"

# checkpoints.save_checkpoint(
#     ckpt_dir=path, target=state, step=batch_count, overwrite=True, prefix=model_name
# )

In [ ]:
def jax_array_memory_usage(array):
    """Calculate the memory usage of a JAX array in bytes."""
    # Get the number of bytes per element based on the data type
    bytes_per_element = array.dtype.itemsize
    # Calculate the total number of elements in the array
    total_elements = np.prod(array.shape)
    # Calculate total memory usage
    memory_usage_bytes = bytes_per_element * total_elements
    return memory_usage_bytes


cat_memory_usage = jax_array_memory_usage(batch.categorical)
num_memory_usage = jax_array_memory_usage(batch.numeric)
memory_usage = cat_memory_usage + num_memory_usage
memory_usage_gb = memory_usage / 1024 / 1024 / 1024
print(f"Memory usage: {memory_usage} bytes")
print(f"Memory usage: {memory_usage_gb} gb")