In [1]:
import jax.numpy as jnp
import jax
from flax import linen as nn
import hephaestus as hp

In [2]:
class PositionalEncoding(nn.Module):
    d_model: int
    dropout: float
    max_len = 10000

    @nn.compact
    def __call__(self, X):
        # dropout = nn.Dropout(self.dropout) train=True
        pe = jnp.zeros((1, self.max_len, self.d_model))
        x = jnp.arange(self.max_len, dtype=jnp.float32).reshape(-1, 1) / jnp.power(
            10000,
            jnp.arange(0, self.d_model, 2, dtype=jnp.float32) / self.d_model,
        )
        pe = pe.at[:, :, 0::2].set(jnp.sin(x))
        pe = pe.at[:, :, 1::2].set(jnp.cos(x))
        X = X + pe[:, : X.shape[1], :]
        # return dropout(X, deterministic=not train)

        return X


encoding_dim, num_steps = 32, 60
pos_encoding = PositionalEncoding(encoding_dim, 0.6)
x = jnp.zeros((3, num_steps, encoding_dim))
init_variables = pos_encoding.init({"params": jax.random.PRNGKey(0)}, x, train=False)
X = pos_encoding.apply(
    init_variables, x, train=True, rngs={"dropout": jax.random.PRNGKey(4)}
)

I0000 00:00:1695596652.641389       1 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.


In [3]:
jax.random.key(3)

Array((), dtype=key<fry>) overlaying:
[0 3]

In [4]:
X.shape

(3, 60, 32)

In [5]:
X[0]

Array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.3329210e+00, ...,
         0.0000000e+00,  4.4456986e-04,  0.0000000e+00],
       [ 2.2732434e+00, -1.0403671e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [ 0.0000000e+00,  2.2496669e+00,  1.4880288e+00, ...,
         0.0000000e+00,  2.5340049e-02,  0.0000000e+00],
       [ 0.0000000e+00,  2.9795033e-01,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -1.9277005e+00,  0.0000000e+00, ...,
         2.4995649e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [6]:
X[1]

Array([[ 0.0000000e+00,  2.5000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  2.5000000e+00],
       [ 0.0000000e+00,  1.3507558e+00,  0.0000000e+00, ...,
         0.0000000e+00,  4.4456986e-04,  0.0000000e+00],
       [ 0.0000000e+00, -1.0403671e+00,  0.0000000e+00, ...,
         0.0000000e+00,  8.8913972e-04,  0.0000000e+00],
       ...,
       [ 1.0904119e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  2.5340049e-02,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  2.3299787e+00, ...,
         0.0000000e+00,  2.5784597e-02,  2.4998670e+00],
       [ 1.5918450e+00, -1.9277005e+00,  2.4543397e+00, ...,
         0.0000000e+00,  0.0000000e+00,  2.4998624e+00]], dtype=float32)

In [7]:
pe = jnp.arange(10).reshape(-1, 1)
pe = pe / jnp.power(100, pe)
pe

Array([[ 0.0000000e+00],
       [ 9.9999998e-03],
       [ 1.9999999e-04],
       [ 3.0000001e-06],
       [ 4.0000000e-08],
       [ 3.5459349e-09],
       [-8.2487839e-09],
       [ 2.5321288e-08],
       [ 4.2668500e-09],
       [-6.0540075e-09]], dtype=float32)

In [8]:
jnp.sin(pe)

Array([[ 0.0000000e+00],
       [ 9.9998331e-03],
       [ 1.9999999e-04],
       [ 3.0000001e-06],
       [ 4.0000000e-08],
       [ 3.5459349e-09],
       [-8.2487839e-09],
       [ 2.5321288e-08],
       [ 4.2668500e-09],
       [-6.0540075e-09]], dtype=float32)

In [9]:
mat = jnp.arange(1728).reshape(3, 9, 64)
print(mat.shape)
mat1 = mat.reshape(-1, 64)
print(mat1.shape)
mat2 = jnp.expand_dims(mat1, axis=0)
print(mat2.shape)

(3, 9, 64)
(27, 64)
(1, 27, 64)


In [10]:
one = jnp.ones((3, 9, 64))
one1 = jnp.ones((9, 64))

In [11]:
jnp.matmul(mat, jnp.swapaxes(mat, -2, -1)).shape

(3, 9, 9)

In [12]:
jnp.matmul(one1, jnp.swapaxes(mat2, -2, -1)).shape

(1, 9, 27)

In [13]:
mat.reshape(-1, 4).shape

(432, 4)

In [14]:
mat2 = jnp.ones((3, 9, 64))

In [15]:
mat3 = 

SyntaxError: invalid syntax (941626681.py, line 1)

In [ ]:
mat3.reshape(-1).shape

(1728,)

In [ ]:
jnp.expand_dims(mat3, axis=0).shape

(1, 27, 64)