In [82]:
import jax.numpy as jnp
import jax
from flax import linen as nn
import .hephaestus as hp


SyntaxError: invalid syntax (2507582064.py, line 4)

In [59]:
class PositionalEncoding(nn.Module):
    d_model: int
    dropout: float
    max_len = 1000

    @nn.compact
    def __call__(self, X, train=True):
        dropout = nn.Dropout(self.dropout)
        pe = jnp.zeros((1, self.max_len, self.d_model))
        x = jnp.arange(self.max_len, dtype=jnp.float32).reshape(-1, 1) / jnp.power(
            10000,
            jnp.arange(0, self.d_model, 2, dtype=jnp.float32) / self.d_model,
        )
        pe = pe.at[:, :, 0::2].set(jnp.sin(x))
        pe = pe.at[:, :, 1::2].set(jnp.cos(x))
        X = X + pe[:, : X.shape[1], :]
        return dropout(X, deterministic=not train)


encoding_dim, num_steps = 32, 60
pos_encoding = PositionalEncoding(encoding_dim, 0.6)
x = jnp.zeros((3, num_steps, encoding_dim))
init_variables = pos_encoding.init({"params": jax.random.PRNGKey(0)}, x, train=False)
X = pos_encoding.apply(
    init_variables, x, train=True, rngs={"dropout": jax.random.PRNGKey(4)}
)

In [60]:
jax.random.key(3)

Array((), dtype=key<fry>) overlaying:
[0 3]

In [63]:
X.shape

(3, 60, 32)

In [64]:
X[0]

Array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.3329210e+00, ...,
         0.0000000e+00,  4.4456986e-04,  0.0000000e+00],
       [ 2.2732434e+00, -1.0403671e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       ...,
       [ 0.0000000e+00,  2.2496669e+00,  1.4880288e+00, ...,
         0.0000000e+00,  2.5340049e-02,  0.0000000e+00],
       [ 0.0000000e+00,  2.9795033e-01,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -1.9277005e+00,  0.0000000e+00, ...,
         2.4995649e+00,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [65]:
X[1]

Array([[ 0.0000000e+00,  2.5000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  0.0000000e+00,  2.5000000e+00],
       [ 0.0000000e+00,  1.3507558e+00,  0.0000000e+00, ...,
         0.0000000e+00,  4.4456986e-04,  0.0000000e+00],
       [ 0.0000000e+00, -1.0403671e+00,  0.0000000e+00, ...,
         0.0000000e+00,  8.8913972e-04,  0.0000000e+00],
       ...,
       [ 1.0904119e+00,  0.0000000e+00,  0.0000000e+00, ...,
         0.0000000e+00,  2.5340049e-02,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  2.3299787e+00, ...,
         0.0000000e+00,  2.5784597e-02,  2.4998670e+00],
       [ 1.5918450e+00, -1.9277005e+00,  2.4543397e+00, ...,
         0.0000000e+00,  0.0000000e+00,  2.4998624e+00]], dtype=float32)

In [74]:
pe = jnp.arange(10).reshape(-1, 1)
pe = pe / jnp.power(100, pe)
pe

Array([[ 0.0000000e+00],
       [ 9.9999998e-03],
       [ 1.9999999e-04],
       [ 3.0000001e-06],
       [ 4.0000000e-08],
       [ 3.5459349e-09],
       [-8.2487839e-09],
       [ 2.5321288e-08],
       [ 4.2668500e-09],
       [-6.0540075e-09]], dtype=float32)

In [71]:
jnp.sin(pe)

Array([[ 0.841471  ],
       [-0.30561438],
       [ 0.931639  ],
       [-0.518611  ],
       [ 0.9909816 ],
       [-0.20013674],
       [-0.10385309],
       [-0.98619825],
       [ 0.        ],
       [ 0.        ]], dtype=float32)

In [78]:
mat = jnp.arange(128).reshape(8, 4, 4)
mat.shape

(8, 4, 4)

In [79]:
mat

Array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]],

       [[ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31]],

       [[ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]],

       [[ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79]],

       [[ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111]],

       [[112, 113, 114, 115],
        [116, 117, 118, 119],
        [120, 121, 122, 123],
        [124, 125, 126, 127]]], dtype=int32)

In [ ]:
ts = hp.