In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import torch.nn.functional as F

import numpy as np

# Load and preprocess the dataset (assuming you have a CSV file)
df = pd.read_csv("../data/diamonds.csv")
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [2]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [3]:
from itertools import chain

In [4]:
cat_columns = ["cut", "color", "clarity"]
num_columns = ["carat", "depth", "table", "x", "y", "z"]
cat_values = pd.unique(df[cat_columns].values.ravel("K"))
target_column = "price"
tokens = list(chain(cat_values, cat_columns, num_columns, [target_column]))
token_dict = {token: i for i, token in enumerate(tokens)}

In [5]:
embedding = nn.Embedding(len(token_dict), 64)
cat_values_emb = torch.tensor(
    [[token_dict[token] for token in row] for row in df[cat_columns].values],
    dtype=torch.long,
)

col_names_emb = torch.tensor([token_dict[col] for col in df.columns], dtype=torch.long)
embedding(col_names_emb).shape

torch.Size([10, 64])

In [6]:
X = df.drop("price", axis=1)
y = df["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Preprocess categorical features
X_train_cat = X_train[cat_columns].copy()
X_test_cat = X_test[cat_columns].copy()

label_encoders = {}
for col in cat_columns:
    le = LabelEncoder()
    X_train_cat[col] = X_train_cat[col].map(token_dict)
    X_test_cat[col] = X_test_cat[col].map(token_dict)
    # label_encoders[col] = le

# Preprocess numeric features

scaler = StandardScaler()
X_train_num = scaler.fit_transform(X_train[num_columns].copy())
X_test_num = scaler.transform(X_test[num_columns].copy())

X_train_cat_tensor = torch.tensor(
    X_train_cat.values, dtype=torch.int64
)  # Use int64 dtype for categorical indices
X_train_num_tensor = torch.tensor(X_train_num, dtype=torch.float32)
X_test_cat_tensor = torch.tensor(
    X_test_cat.values, dtype=torch.int64
)  # Use int64 dtype for categorical indices
X_test_num_tensor = torch.tensor(X_test_num, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1, 1)

In [7]:
X_test_cat

cut  color  clarity
1388     0     10       17
50052    3      9       16
41645    0      5       16
42377    1      5       16
17244    0      5       12
...    ...    ...      ...
44081    3      5       14
23713    3      9       16
31375    2     10       17
21772    0      9       14
4998     2      7       12

[10788 rows x 3 columns]

In [8]:
input_tensor = torch.randn(10, 6)
repeated_tensor = input_tensor.unsqueeze(1).repeat(1, 4, 1)

print(repeated_tensor.shape)

torch.Size([10, 4, 6])


In [9]:
X_train_num_tensor[0:10, :].unsqueeze(2).shape

torch.Size([10, 6, 1])

In [10]:
class NumericEmbedding(nn.Module):
    def __init__(self, d_model=64):
        super(NumericEmbedding, self).__init__()
        self.d_model = d_model
        self.linear = nn.Sequential(
            nn.Linear(1, d_model),
            nn.ReLU(),
            nn.Linear(d_model, 64),
        )

    def forward(self, numeric_tensor, first_four=False):
        if first_four:
            if numeric_tensor.ndim == 2:
                numeric_tensor = numeric_tensor.unsqueeze(2).repeat(1, 1, 4)
            elif numeric_tensor.ndim == 1:
                numeric_tensor = numeric_tensor.repeat(1, 1, 4)
            else:
                raise ValueError("numeric_tensor must be 1D or 2D")

            zero_embd = torch.zeros(
                numeric_tensor.size(0),
                numeric_tensor.size(1),
                self.d_model - numeric_tensor.size(2),
            )
            out = torch.cat([numeric_tensor, zero_embd], dim=2)
            return out
        else:
            numeric_tensor = numeric_tensor.unsqueeze(2)
            return self.linear(numeric_tensor)


numeric_embedding = NumericEmbedding()
test_embd = numeric_embedding(X_train_num_tensor[0:10, :])
test_embd.shape

torch.Size([10, 6, 64])

In [11]:
test_mat = torch.rand(3, 4, 5)
test_mat

tensor([[[0.1604, 0.3445, 0.6978, 0.1998, 0.9735],
         [0.0732, 0.3774, 0.1966, 0.3286, 0.8781],
         [0.0419, 0.2574, 0.0638, 0.5357, 0.6163],
         [0.1152, 0.6667, 0.7150, 0.9101, 0.0605]],

        [[0.1252, 0.6849, 0.1274, 0.4090, 0.4373],
         [0.0774, 0.4272, 0.1606, 0.8175, 0.1027],
         [0.0342, 0.7487, 0.0200, 0.7496, 0.6971],
         [0.7681, 0.6832, 0.4315, 0.6218, 0.6027]],

        [[0.7934, 0.8341, 0.0767, 0.0806, 0.9866],
         [0.4993, 0.8700, 0.8879, 0.0983, 0.0296],
         [0.6950, 0.9392, 0.5446, 0.4494, 0.7049],
         [0.3332, 0.5412, 0.8769, 0.1278, 0.1010]]])

In [12]:
test_mat[0, 0], test_mat[0, 0] * 10

(tensor([0.1604, 0.3445, 0.6978, 0.1998, 0.9735]),
 tensor([1.6040, 3.4446, 6.9776, 1.9976, 9.7349]))

In [13]:
(X_train_num_tensor[0:10, :].shape, X_train_num_tensor[0:10, :].unsqueeze(2).shape)

(torch.Size([10, 6]), torch.Size([10, 6, 1]))

In [14]:
scalars = torch.tensor([10, 2, 3, 4])
scalars = scalars.unsqueeze(1).unsqueeze(0)
scalars.shape

torch.Size([1, 4, 1])

In [15]:
double_test_mat = scalars * test_mat
double_test_mat

tensor([[[1.6040, 3.4446, 6.9776, 1.9976, 9.7349],
         [0.1464, 0.7547, 0.3932, 0.6572, 1.7562],
         [0.1258, 0.7723, 0.1913, 1.6071, 1.8490],
         [0.4609, 2.6668, 2.8600, 3.6402, 0.2420]],

        [[1.2524, 6.8493, 1.2741, 4.0903, 4.3732],
         [0.1548, 0.8543, 0.3212, 1.6350, 0.2055],
         [0.1025, 2.2462, 0.0600, 2.2489, 2.0914],
         [3.0726, 2.7328, 1.7261, 2.4870, 2.4109]],

        [[7.9344, 8.3407, 0.7668, 0.8060, 9.8656],
         [0.9986, 1.7401, 1.7758, 0.1966, 0.0592],
         [2.0851, 2.8177, 1.6337, 1.3481, 2.1147],
         [1.3330, 2.1647, 3.5076, 0.5110, 0.4040]]])

In [16]:
double_test_mat[0, 0]

tensor([1.6040, 3.4446, 6.9776, 1.9976, 9.7349])

In [17]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super(MultiHeadAttention, self).__init__()
        self.num_heads = num_heads
        self.d_model = d_model
        self.d_head = d_model // num_heads

        self.q_linear = nn.Linear(d_model, d_model)
        self.k_linear = nn.Linear(d_model, d_model)
        self.v_linear = nn.Linear(d_model, d_model)
        self.out_linear = nn.Linear(d_model, d_model)

    def forward(self, q, k, v, mask=None):
        batch_size = q.size(0)

        q = (
            self.q_linear(q)
            .view(batch_size, -1, self.num_heads, self.d_head)
            .transpose(1, 2)
        )
        k = (
            self.k_linear(k)
            .view(batch_size, -1, self.num_heads, self.d_head)
            .transpose(1, 2)
        )
        v = (
            self.v_linear(v)
            .view(batch_size, -1, self.num_heads, self.d_head)
            .transpose(1, 2)
        )

        attn_output, _ = self.scaled_dot_product_attention(q, k, v, mask)

        attn_output = (
            attn_output.transpose(1, 2).contiguous().view(batch_size, -1, self.d_model)
        )
        out = self.out_linear(attn_output)
        return out

    def scaled_dot_product_attention(self, q, k, v, mask=None):
        matmul_qk = torch.matmul(q, k.transpose(-2, -1))
        d_k = q.size(-1)
        scaled_attention_logits = matmul_qk / (d_k**0.5)

        if mask is not None:
            scaled_attention_logits += mask * -1e9

        attention_weights = F.softmax(scaled_attention_logits, dim=-1)
        output = torch.matmul(attention_weights, v)

        return output, attention_weights


class TransformerEncoderLayer(nn.Module):
    def __init__(self, d_model, num_heads):
        super(TransformerEncoderLayer, self).__init__()

        self.multi_head_attention = MultiHeadAttention(d_model, num_heads)

        self.feed_forward = nn.Sequential(
            nn.Linear(d_model, 4 * d_model),
            nn.ReLU(),
            nn.Linear(4 * d_model, d_model),
        )

        self.layernorm1 = nn.LayerNorm(d_model)
        self.layernorm2 = nn.LayerNorm(d_model)

    def forward(self, q, k, v, mask=None):
        attn_output = self.multi_head_attention(q, k, v, mask)
        out1 = self.layernorm1(q + attn_output)

        ff_output = self.feed_forward(out1)
        out2 = self.layernorm2(out1 + ff_output)

        return out2


# Parameters
d_model = 64  # Embedding dimension
num_heads = 4  # Number of attention heads
seq_len_q = 10  # Sequence length for the query tensor
seq_len_k = 20  # Sequence length for the key tensor
batch_size = 32  # Batch size

# Random data
q = torch.rand((batch_size, seq_len_q, d_model))
k = torch.rand((batch_size, seq_len_k, d_model))
v = k  # Usually, value and key are the same in many applications

# Model
encoder_layer = TransformerEncoderLayer(d_model, num_heads)

# Forward pass
output = encoder_layer(q, k, v)
print("Output shape:", output.shape)

Output shape: torch.Size([32, 10, 64])


In [18]:
df.head().drop("price", axis=1)

carat      cut color clarity  depth  table     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75

In [19]:
[1, 2, 3] + [4, 5, 6]

[1, 2, 3, 4, 5, 6]

In [20]:
class TabTransformer(nn.Module):
    def __init__(
        self,
        tokens,
        numeric_col_tokens,
        cat_col_tokens,
        d_model=64,
    ):
        super(TabTransformer, self).__init__()
        self.d_model = d_model
        self.tokens = tokens
        self.col_tokens = cat_col_tokens + numeric_col_tokens
        self.n_tokens = len(tokens)  # TODO Make this
        # Embedding layers for categorical features
        self.embeddings = nn.Embedding(self.n_tokens, self.d_model)
        self.n_num_embeddings = 6
        # self.numeric_embeddings = NumericEmbedding(d_model=self.d_model)
        self.col_indices = torch.tensor(
            [self.tokens.index(col) for col in self.col_tokens], dtype=torch.long
        )
        self.numeric_indices = torch.tensor(
            [self.tokens.index(col) for col in numeric_col_tokens], dtype=torch.long
        )
        self.transformer_encoder = TransformerEncoderLayer(d_model, num_heads=4)

        self.numeric_predictor = nn.Sequential(
            nn.Linear(d_model, d_model * 2),
            nn.ReLU(),
            nn.Linear(d_model * 2, 1),
            nn.ReLU(),
        )

        self.flatten_layer = nn.Linear(len(self.col_tokens), 1)

    def forward(self, num_inputs, cat_inputs):
        # Embed column indices
        repeated_col_indices = self.col_indices.unsqueeze(0).repeat(
            num_inputs.size(0), 1
        )
        col_embeddings = self.embeddings(repeated_col_indices)

        repeated_numeric_indices = self.numeric_indices.unsqueeze(0).repeat(
            num_inputs.size(0), 1
        )
        numeric_col_embeddings = self.embeddings(repeated_numeric_indices)

        cat_embeddings = self.embeddings(cat_inputs)
        # num_embeddings = self.numeric_embeddings(num_inputs)
        expanded_num_inputs = num_inputs.unsqueeze(2).repeat(1, 1, 64)
        # print(
        #     f"NumCol: {numeric_col_embeddings.shape}",
        #     f"NumericInputs: {expanded_num_inputs.shape}",
        #     sep="\n",
        # )
        num_embeddings = numeric_col_embeddings * expanded_num_inputs
        # Put a multiplier of the numeric embeddings and the
        # numeric columns to embed the numeric weights instead of the lame ass
        # embedder you currently have.
        # return col_embeddings, cat_embeddings, num_embeddings
        query_embeddings = torch.cat([cat_embeddings, num_embeddings], dim=1)
        out = self.transformer_encoder(
            col_embeddings,
            query_embeddings,
            query_embeddings
            # col_embeddings, query_embeddings, query_embeddings
        )
        out = self.numeric_predictor(out)
        out = self.flatten_layer(out.squeeze(-1))
        return out


no_price_tokens = tokens.copy()
no_price_tokens.remove("price")

numeric_col_tokens = (
    df.head().drop("price", axis=1).select_dtypes(include=np.number).columns.to_list()
)
cat_col_tokens = df.head().select_dtypes(exclude=np.number).columns.to_list()

model = TabTransformer(
    no_price_tokens,
    numeric_col_tokens=numeric_col_tokens,
    cat_col_tokens=cat_col_tokens,
)
x = model(X_train_num_tensor[0:32, :], X_train_cat_tensor[0:32, :])
x.shape

torch.Size([32, 1])

In [21]:
epochs = 40
batch_size = 1000
lr = 0.001
loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=lr)
batch_count = 0
model.train()
for epoch in range(epochs):
    for i in range(0, X_train_num_tensor.size(0), batch_size):
        optimizer.zero_grad()
        y_pred = model(
            X_train_num_tensor[i : i + batch_size, :],
            X_train_cat_tensor[i : i + batch_size, :],
        )
        loss = loss_fn(y_pred, y_train_tensor[i : i + batch_size, :])
        loss.backward()
        optimizer.step()
        batch_count += 1
        if batch_count % 100 == 0:
            print(f"Epoch {epoch+1}/{epochs} Loss: {loss.item():,.2f}")

Epoch 3/100 Loss: 26,001,790.00
Epoch 5/100 Loss: 21,874,858.00
Epoch 7/100 Loss: 7,554,384.50
Epoch 10/100 Loss: 1,631,678.00
Epoch 12/100 Loss: 742,269.44
Epoch 14/100 Loss: 485,216.91
Epoch 16/100 Loss: 288,242.59
Epoch 19/100 Loss: 412,795.25
Epoch 21/100 Loss: 324,930.38
Epoch 23/100 Loss: 284,899.25
Epoch 25/100 Loss: 402,650.69
Epoch 28/100 Loss: 402,396.22
Epoch 30/100 Loss: 281,483.47
Epoch 32/100 Loss: 370,100.12
Epoch 35/100 Loss: 271,378.22
Epoch 37/100 Loss: 295,787.22
Epoch 39/100 Loss: 347,235.66
Epoch 41/100 Loss: 288,962.88
Epoch 44/100 Loss: 332,677.62
Epoch 46/100 Loss: 305,817.09
Epoch 48/100 Loss: 251,425.47
Epoch 50/100 Loss: 325,339.59
Epoch 53/100 Loss: 367,920.28
Epoch 55/100 Loss: 269,086.44
Epoch 57/100 Loss: 340,613.38
Epoch 60/100 Loss: 259,414.55
Epoch 62/100 Loss: 282,344.12
Epoch 64/100 Loss: 332,069.25
Epoch 66/100 Loss: 290,322.22
Epoch 69/100 Loss: 318,891.00
Epoch 71/100 Loss: 289,071.50
Epoch 73/100 Loss: 245,454.20
Epoch 75/100 Loss: 272,653.91
Epo

In [75]:
with torch.no_grad():
    y_pred = model(X_test_num_tensor[0:10, :], X_test_cat_tensor[0:10, :])
    loss = loss_fn(y_pred, y_test_tensor[0:10])
    print(f"Test loss: {loss.item():,.2f}")

Test loss: 985,492.12


In [77]:
for i in range(10):
    print(
        f"Predicted: {y_pred[i].item():,.2f} Actual: {y_test_tensor[i].item():,.2f}",
        f"Diff: {y_pred[i].item() - y_test_tensor[i].item():,.2f}",
    )

Predicted: 601.22 Actual: 559.00 Diff: 42.22
Predicted: 2,328.35 Actual: 2,201.00 Diff: 127.35
Predicted: 1,207.12 Actual: 1,238.00 Diff: -30.88
Predicted: 1,467.03 Actual: 1,304.00 Diff: 163.03
Predicted: 9,597.38 Actual: 6,901.00 Diff: 2,696.38
Predicted: 3,875.39 Actual: 3,011.00 Diff: 864.39
Predicted: 1,825.58 Actual: 1,765.00 Diff: 60.58
Predicted: 1,854.22 Actual: 1,679.00 Diff: 175.22
Predicted: 2,105.56 Actual: 2,102.00 Diff: 3.56
Predicted: 6,114.66 Actual: 4,789.00 Diff: 1,325.66


In [ ]:
for i in range(10):
    print(f"Predicted: {y_pred[i].item():,.2f} Actual: {y_test_tensor[i].item():,.2f}")

Predicted: 754.16 Actual: 559.00
Predicted: 2,390.27 Actual: 2,201.00
Predicted: 993.24 Actual: 1,238.00
Predicted: 1,583.13 Actual: 1,304.00
Predicted: 9,786.17 Actual: 6,901.00
Predicted: 3,888.29 Actual: 3,011.00
Predicted: 1,574.12 Actual: 1,765.00
Predicted: 1,755.46 Actual: 1,679.00
Predicted: 2,334.63 Actual: 2,102.00
Predicted: 5,939.16 Actual: 4,789.00


In [ ]:
for i in range(10):
    print(f"Predicted: {y_pred[i].item():,.2f} Actual: {y_test_tensor[i].item():,.2f}")

Predicted: 688.47 Actual: 559.00
Predicted: 2,547.17 Actual: 2,201.00
Predicted: 1,044.95 Actual: 1,238.00
Predicted: 1,790.95 Actual: 1,304.00
Predicted: 10,160.45 Actual: 6,901.00
Predicted: 3,790.90 Actual: 3,011.00
Predicted: 1,729.77 Actual: 1,765.00
Predicted: 1,749.63 Actual: 1,679.00
Predicted: 2,328.92 Actual: 2,102.00
Predicted: 5,928.75 Actual: 4,789.00


In [ ]:
# Predicted: 688.47 Actual: 559.00
# Predicted: 2,547.17 Actual: 2,201.00
# Predicted: 1,044.95 Actual: 1,238.00
# Predicted: 1,790.95 Actual: 1,304.00
# Predicted: 10,160.45 Actual: 6,901.00
# Predicted: 3,790.90 Actual: 3,011.00
# Predicted: 1,729.77 Actual: 1,765.00
# Predicted: 1,749.63 Actual: 1,679.00
# Predicted: 2,328.92 Actual: 2,102.00
# Predicted: 5,928.75 Actual: 4,789.00